//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orquesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PEDIDO
    {
        public int Id_Detalle_Pedido { get; set; }
        public int Id_Pedido { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Id_Articulo { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
