//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orquesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_INVENTARIO
    {
        public int Id_Detalle_Inventario { get; set; }
        public int Id_Articulo { get; set; }
        public int Id_Ubicacion { get; set; }
        public int Id_Inventario { get; set; }
    
        public virtual ARTICULO ARTICULO { get; set; }
        public virtual INVENTARIO INVENTARIO { get; set; }
        public virtual UBICACION UBICACION { get; set; }
    }
}
