//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orquesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTARIO()
        {
            this.DETALLE_INVENTARIO = new HashSet<DETALLE_INVENTARIO>();
        }
    
        public int Id_Inventario { get; set; }
        public Nullable<int> Id_Canal { get; set; }
        public string Fac_numero { get; set; }
        public Nullable<System.DateTime> Fec_ingreso { get; set; }
        public string Proveedor { get; set; }
        public Nullable<System.DateTime> Fec_Factura { get; set; }
        public string Propietario { get; set; }
    
        public virtual CANAL CANAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_INVENTARIO> DETALLE_INVENTARIO { get; set; }
    }
}
