//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orquesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL_OPERACION
    {
        public int Id { get; set; }
        public int Id_Rol { get; set; }
        public int Id_Operacion { get; set; }
    
        public virtual OPERACIONES OPERACIONES { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
